import { useEffect, useMemo, useRef, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Command } from "cmdk";
import { ArrowRight, Check, CheckCircle, CaretDown, CircleNotch, Clock, File, Folder, GearSix, GitDiff, List, MagnifyingGlass, Play, Plus, Robot, ShieldCheck, Sparkle, Trash, UsersThree, WarningCircle, X } from "@phosphor-icons/react";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { useI18n } from "./i18n.jsx";
import logoUrl from "./assets/habor-logo.png";

const FALLBACK = import.meta.env.VITE_HABOR_APP_SERVER_URL || "http://127.0.0.1:52197";
const STARTERS = [{ key:"starterTask", prompt:"starterTaskPrompt" }, { key:"starterPlan", prompt:"starterPlanPrompt" }];
const local = () => { try { return JSON.parse(localStorage.getItem("habor.desktop.local") || "{}"); } catch { return {}; } };
const time = (value) => new Intl.DateTimeFormat(undefined, { hour:"numeric", minute:"2-digit" }).format(new Date(value || Date.now()));

export function App() {
  const { t } = useI18n();
  const [url, setUrl] = useState("");
  const [error, setError] = useState("");
  const [snapshot, setSnapshot] = useState(null);
  const [taskId, setTaskId] = useState(local().taskId || null);
  const [model, setModel] = useState(local().model || "");
  const [permission, setPermission] = useState("ask");
  const [draft, setDraft] = useState("");
  const [mode, setMode] = useState("solo");
  const [context, setContext] = useState(null);
  const [panel, setPanel] = useState(null);
  const [commandOpen, setCommandOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [approval, setApproval] = useState(null);
  const [log, setLog] = useState([]);
  const composer = useRef(null);
  const task = useMemo(() => snapshot?.tasks?.find((item) => item.id === taskId) || null, [snapshot, taskId]);
  const models = snapshot?.models || [];

  async function rpc(method, params = {}) {
    if (url === "ipc") return invoke("server_request", { method, params });
    if (!url) throw new Error(t("serverNotReady"));
    const response = await fetch(url + "/rpc", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ id:crypto.randomUUID(), method, params }) });
    const body = await response.json();
    if (!response.ok || body.error) throw new Error(body.error || t("requestFailed"));
    return body.result;
  }
  async function refresh() { setSnapshot(await rpc("snapshot", { refresh:true })); }
  async function connect() {
    let next = "ipc";
    try {
      const result = await invoke("server_request", { method:"snapshot", params:{ refresh:true } });
      setUrl("ipc"); setSnapshot(result); setModel(model || result.models?.find((item) => item.available)?.model || result.models?.[0]?.model || ""); if (!taskId && result.tasks?.[0]) setTaskId(result.tasks[0].id); return;
    } catch {}
    next = FALLBACK;
    try { const response = await fetch(next + "/rpc", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ id:"snapshot", method:"snapshot" }) }); if (!response.ok) throw new Error(t("serverUnavailable")); const body=await response.json(); setUrl(next); setSnapshot(body.result); setModel(model || body.result.models?.find((item) => item.available)?.model || body.result.models?.[0]?.model || ""); if (!taskId && body.result.tasks?.[0]) setTaskId(body.result.tasks[0].id); }
    catch (cause) { setError(cause.message); }
  }
  useEffect(() => { connect(); }, []);
  useEffect(() => { localStorage.setItem("habor.desktop.local", JSON.stringify({ taskId, model })); }, [taskId, model]);
  useEffect(() => {
    if (!url || url === "ipc") return;
    const source = new EventSource(url + "/events");
    source.onmessage = (message) => { try { const event = JSON.parse(message.data); if (event.type === "approval") setApproval(event.approval); if (event.type === "operation") setLog((items) => [...items.slice(-60), event.operation]); if (event.type === "task") setSnapshot((current) => current ? {...current, tasks:[...(current.tasks || []).filter((item) => item.id !== event.task.id), event.task].sort((a,b) => b.updatedAt-a.updatedAt)} : current); } catch {} };
    return () => source.close();
  }, [url]);
  useEffect(() => {
    let cleanup;
    listen("habor:menu", (event) => { if (event.payload === "new-task") newTask(); if (event.payload === "command-palette") setCommandOpen(true); }).then((value) => { cleanup = value; }).catch(() => {});
    return () => cleanup?.();
  }, []);
  useEffect(() => { const key = (event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommandOpen(true); } }; window.addEventListener("keydown",key); return () => window.removeEventListener("keydown",key); }, []);

  async function trust() { try { await rpc("workspace.trust", { path:snapshot.cwd }); await refresh(); } catch (cause) { setError(cause.message); } }
  async function createTask(text) {
    if (!text.trim() || !model) return; setBusy(true);
    try { const result=await rpc("tasks.create",{title:text.trim().slice(0,90),model,permission}); setTaskId(result.id); setDraft(""); await send(result.id,text.trim()); } catch (cause) { setError(cause.message); } finally { setBusy(false); }
  }
  async function send(id=taskId,text=draft) {
    if (!id || !text.trim()) return; setBusy(true); setDraft("");
    try { const result=await rpc("tasks.send",{taskId:id,input:text.trim()}); if(result?.task) setTaskId(result.task.id); await refresh(); } catch (cause) { setError(cause.message); } finally { setBusy(false); }
  }
  async function changeModel(next) {
    if (!task || next === task.harnessProfile?.model) return; setBusy(true);
    try { await rpc("tasks.model",{taskId:task.id,model:next}); await refresh(); } catch (cause) { setError(cause.message); } finally { setBusy(false); }
  }
  async function decide(allow) { if (!approval) return; try { await rpc("approval.resolve",{id:approval.id,allow,optionId:approval.options?.[0]?.id}); setApproval(null); } catch (cause) { setError(cause.message); } }
  function newTask() { setTaskId(null); setDraft(""); setMode("solo"); setContext(null); requestAnimationFrame(() => composer.current?.focus()); }

  return <main className="app-shell">
    <header className="titlebar"><div className="brand"><div className="brand-mark"><img src={logoUrl} alt="" /></div><span>habor</span><CaretDown size={13} /></div><div className="titlebar-task"><span className="crumb">{snapshot?.cwd || "workspace"}</span><span className="slash">/</span><span>{task?.title || t("newTask")}</span>{url && <span className="connection-status"><span className="status-dot done" /> {t("connected")}</span>}</div><div className="titlebar-actions"><LanguagePicker /><button className="command-trigger" onClick={() => setCommandOpen(true)}><MagnifyingGlass size={15} /><span>{t("search")}</span><kbd>⌘K</kbd></button><button className="icon-btn" onClick={() => setPanel("settings")} aria-label={t("settings")}><GearSix size={18} /></button></div></header>
    <div className={"workspace-grid " + (context ? "with-context" : "without-context")}><Sidebar snapshot={snapshot} taskId={taskId} onNew={newTask} onSearch={() => setCommandOpen(true)} onSelect={(item) => { setTaskId(item.id); setMode("solo"); }} onTeams={() => setMode("collaborate")} onAgents={() => setPanel("agents")} onHistory={() => setPanel("history")} onSettings={() => setPanel("settings")} /><section className="main-column"><div className="task-toolbar"><div className="task-heading"><div className={"status-pill " + (task ? "" : "quiet")}><span className="pulse" /> {task ? (busy ? t("running") : t("ready")) : t("newTask")}</div><h1>{task?.title || t("newTask")}</h1>{task && <span className="task-id">{task.harnessProfile?.model || t("modelNotSelected")}</span>}</div><div className="task-controls"><div className="mode-switch"><button className={mode === "solo" ? "active" : ""} onClick={() => setMode("solo")}>{t("solo")}</button><button className={mode === "collaborate" ? "active" : ""} onClick={() => setMode("collaborate")}>{t("collaborate")}</button></div>{task && <button className={"context-toggle " + (context ? "active" : "")} onClick={() => setContext(context ? null : "files")}><GitDiff size={15} /> {context ? t("close") : t("context")}</button>}</div></div>{mode === "collaborate" ? <CollabView task={task} models={models.filter((item) => item.available)} rpc={rpc} refresh={refresh} onError={setError} /> : task ? <TaskView task={task} models={models} draft={draft} setDraft={setDraft} composer={composer} send={() => send()} changeModel={changeModel} busy={busy} approval={approval} decide={decide} setContext={setContext} /> : <EmptyTask trusted={snapshot?.trusted} models={models} model={model} setModel={setModel} permission={permission} setPermission={setPermission} draft={draft} setDraft={setDraft} composer={composer} createTask={createTask} trust={trust} onAgents={() => setPanel("agents")} busy={busy} />}</section>{context && <ContextPanel tab={context} setTab={setContext} rpc={rpc} />}</div>
    {approval && <div className="approval-toast"><div><strong>{t("approvalNeeded")}</strong><span>{approval.description}</span></div><button className="approve" onClick={() => decide(true)}><Check size={14} /> {t("allowOnce")}</button><button className="deny" onClick={() => decide(false)}>{t("deny")}</button></div>}
    {error && <div className="error-toast"><WarningCircle size={16} /><span>{error}</span><button className="icon-btn" onClick={() => setError("")}><X size={15} /></button></div>}
    {panel === "history" && <Dialog.Root open onOpenChange={(open) => !open && setPanel(null)}><Dialog.Portal><Dialog.Overlay className="command-overlay" /><Dialog.Content className="side-dialog"><Dialog.Title>{t("history")}</Dialog.Title><HistoryPanel rpc={rpc} model={model} onSelect={async (item) => { setTaskId(item.id); await refresh(); setPanel(null); }} onError={setError} /></Dialog.Content></Dialog.Portal></Dialog.Root>}
    {panel === "agents" && <Dialog.Root open onOpenChange={(open) => !open && setPanel(null)}><Dialog.Portal><Dialog.Overlay className="command-overlay" /><Dialog.Content className="side-dialog"><Dialog.Title>{t("agentsAndModels")}</Dialog.Title><AgentsPanel snapshot={snapshot} rpc={rpc} refresh={refresh} log={log} onError={setError} /></Dialog.Content></Dialog.Portal></Dialog.Root>}
    {panel === "settings" && <Dialog.Root open onOpenChange={(open) => !open && setPanel(null)}><Dialog.Portal><Dialog.Overlay className="command-overlay" /><Dialog.Content className="side-dialog"><Dialog.Title>{t("settings")}</Dialog.Title><SettingsPanel snapshot={snapshot} url={url} rpc={rpc} refresh={refresh} /></Dialog.Content></Dialog.Portal></Dialog.Root>}
    <CommandPalette open={commandOpen} setOpen={setCommandOpen} onNew={newTask} onAgents={() => setPanel("agents")} onSettings={() => setPanel("settings")} onContext={setContext} />
  </main>;
}

function LanguagePicker() { const { preference,languages,setLanguage,t }=useI18n(); return <label className="language-picker" title={t("language")}><span className="language-globe">文</span><select aria-label={t("language")} value={preference} onChange={(e)=>setLanguage(e.target.value)}>{languages.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select><CaretDown size={12}/></label>; }
function Sidebar({ snapshot,taskId,onNew,onSearch,onSelect,onTeams,onAgents,onHistory,onSettings }) { const {t}=useI18n();const tasks=snapshot?.tasks||[];return <aside className="sidebar"><div className="sidebar-top"><button className="new-task" onClick={onNew}><Plus size={16} weight="bold"/>{t("newTask")}</button></div><nav className="primary-nav"><button className="nav-row" onClick={onSearch}><MagnifyingGlass size={16}/><span>{t("search")}</span><kbd>⌘K</kbd></button><button className="nav-row" onClick={onTeams}><UsersThree size={16}/><span>{t("teams")}</span></button><button className="nav-row" onClick={onAgents}><Robot size={16}/><span>{t("agentsAndModels")}</span></button><button className="nav-row" onClick={onHistory}><Clock size={16}/><span>{t("history")}</span></button></nav><div className="sidebar-section task-section"><div className="section-label"><span>{t("recentTasks")}</span><span className="count">{tasks.length}</span></div>{tasks.length?tasks.map((item)=><button key={item.id} className={"task-row "+(item.id===taskId?"selected":"")} onClick={()=>onSelect(item)}><span className={"status-dot "+(item.status==="active"?"working":"done")}/><span className="task-title">{item.title}</span><span className="task-time">{time(item.updatedAt)}</span></button>):<div className="sidebar-empty">{t("noRecentTasks")}</div>}</div><div className="sidebar-section"><div className="section-label">{t("workflows")}</div><button className="template-row" onClick={onNew}><List size={15}/>{t("starterTask")}<ArrowRight size={13}/></button><button className="template-row" onClick={onTeams}><UsersThree size={15}/>{t("collaborate")}<ArrowRight size={13}/></button></div><div className="sidebar-footer"><button className="footer-row" onClick={onSettings}><GearSix size={16}/>{t("settings")}</button><div className="sidebar-note"><CheckCircle size={14}/>{snapshot?.trusted?t("workspaceTrusted"):t("workspaceNeedsTrust")}</div></div></aside>; }
function EmptyTask({trusted,models,model,setModel,permission,setPermission,draft,setDraft,composer,createTask,trust,onAgents,busy}) { const {t}=useI18n();return <div className="empty-task"><div className="empty-task-copy"><div className="empty-mark"><img src={logoUrl} alt="" /></div><h2>{t("emptyTitle")}</h2><p>{t("emptySubtitle")}</p>{!trusted&&<button className="trust-button" onClick={trust}><ShieldCheck size={15}/>{t("trustWorkspace")}</button>}</div><Composer draft={draft} setDraft={setDraft} composer={composer} send={createTask} disabled={!trusted||!model||busy} models={models} model={model} setModel={setModel} permission={permission} setPermission={setPermission} setup onAgents={onAgents}/><div className="suggestion-row">{STARTERS.map((item)=><button key={item.key} onClick={()=>setDraft(t(item.promptKey))}><span>{t(item.key)}</span><ArrowRight size={14}/></button>)}</div>{trusted&&!models.some((item)=>item.available)&&<div className="empty-warning"><WarningCircle size={15}/>{t("noAgents")}<button onClick={onAgents}>{t("manage")}</button></div>}</div>; }
function TaskView({task,models,draft,setDraft,composer,send,changeModel,busy,approval,decide,setContext}) { const {t}=useI18n();const run=task.runs?.at(-1);return <div className="task-view"><div className="task-meta-strip"><label><span className="muted">{t("model")}</span><select className="inline-select" value={task.harnessProfile?.model||""} onChange={(e)=>changeModel(e.target.value)}>{models.map((item)=><option key={item.model} value={item.model} disabled={!item.available}>{item.model}{item.available?"":" · "+t("unavailable")}</option>)}</select></label><div><span className="muted">{t("permission")}</span><span className="permission-badge"><ShieldCheck size={13}/>{task.harnessProfile?.permission||"ask"}</span></div><div><span className="muted">{t("execution")}</span><span className={"runtime-badge "+(run?.status||"idle")}>{run?.status||t("ready")}</span></div></div><div className="task-tabs"><span className="active">{t("conversation")}</span><button onClick={()=>setContext("files")}>{t("files")}</button><button onClick={()=>setContext("diff")}>{t("diff")}</button><button onClick={()=>setContext("verify")}>{t("verify")}</button></div><div className="conversation-scroll">{(task.conversation||[]).map((message,index)=><div className={"message "+(message.role==="user"?"user":"assistant")} key={String(message.seq||index)}><div className="message-meta"><span className={"message-avatar "+(message.role==="user"?"user":"assistant")}>{message.role==="user"?t("you"):<Sparkle size={13} weight="fill"/>}</span><strong>{message.role==="user"?t("you"):message.model||t("assistant")}</strong><span>{time(message.ts)}</span></div><div className="message-body">{message.text}</div></div>)}{approval&&<ApprovalCard approval={approval} decide={decide}/>} {!task.conversation?.length&&<div className="task-empty-note">{t("emptyTaskHistory")}</div>}</div><Composer draft={draft} setDraft={setDraft} composer={composer} send={send} disabled={busy||!!approval} models={models} model={task.harnessProfile?.model||""} permission={task.harnessProfile?.permission||"ask"}/></div>; }
function ApprovalCard({approval,decide}) { const {t}=useI18n();return <div className="approval-card"><WarningCircle size={18}/><div><strong>{t("approvalNeeded")}</strong><p>{approval.description}</p><code>{approval.toolName||t("agentAction")}</code></div><button className="approve" onClick={()=>decide(true)}><Check size={14}/>{t("allowOnce")}</button><button className="deny" onClick={()=>decide(false)}>{t("deny")}</button></div>; }
function Composer({draft,setDraft,composer,send,disabled,models=[],model="",setModel=()=>{},permission="ask",setPermission=()=>{},setup,onAgents}) { const {t}=useI18n();return <div className="composer"><textarea ref={composer} value={draft} disabled={disabled} onChange={(e)=>setDraft(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}} placeholder={t("messagePlaceholder")}/><div className="composer-bottom"><label className="composer-select"><span className="muted">{t("model")}</span><select value={model} disabled={!setup} onChange={(e)=>setModel(e.target.value)}><option value="">{t("chooseModel")}</option>{models.map((item)=><option key={item.model} value={item.model} disabled={!item.available}>{item.model}{item.available?"":" · "+t("unavailable")}</option>)}</select></label><label className="composer-select"><span className="muted">{t("permission")}</span><select value={permission} disabled={!setup} onChange={(e)=>setPermission(e.target.value)}><option value="ask">{t("ask")}</option><option value="auto">{t("auto")}</option></select></label>{setup&&<button className="secondary-control" onClick={onAgents}><Robot size={14}/>{t("agentsAndModels")}</button>}<span className="composer-spacer"/><button className="send-btn" disabled={disabled} onClick={send} aria-label={t("send")}><ArrowRight size={17} weight="bold"/></button></div></div>; }

function CollabView({task,models,rpc,refresh,onError}) { const {t}=useI18n();const [members,setMembers]=useState([{id:"implement",role:"Implement",model:models[0]?.model||""},{id:"review",role:"Review",model:models[1]?.model||models[0]?.model||""}]);const [input,setInput]=useState("");const [running,setRunning]=useState(false);const update=(id,patch)=>setMembers((items)=>items.map((item)=>item.id===id?{...item,...patch}:item));async function save(){if(!task)return;try{await rpc("team.save",{taskId:task.id,members});}catch(e){onError(e.message);}}async function saveTemplate(){try{await save();await rpc("templates.save",{taskId:task.id,name:task.title+" · workflow"});}catch(e){onError(e.message);}}async function run(){if(!task)return;setRunning(true);try{await save();await rpc("tasks.send",{taskId:task.id,input,workflow:true});await refresh();}catch(e){onError(e.message);}finally{setRunning(false);}}return <div className="collab-view"><div className="collab-header"><div><span className="eyebrow">{t("collaborationWorkflow")}</span><h2>{t("membersAndRoles")}</h2></div><div className="collab-actions"><button className="compact-btn" onClick={()=>setMembers((items)=>[...items,{id:crypto.randomUUID(),role:t("review"),model:models[0]?.model||""}])}><Plus size={14}/>{t("addMember")}</button><button className="compact-btn" onClick={saveTemplate}><Check size={14}/>{t("saveTemplate")}</button></div></div><div className="member-list">{members.map((member)=><div className="member-card" key={member.id}><div className="member-avatar"><Robot size={17}/></div><label><span>{t("role")}</span><input value={member.role} onChange={(e)=>update(member.id,{role:e.target.value})}/></label><label><span>{t("model")}</span><select value={member.model} onChange={(e)=>update(member.id,{model:e.target.value})}><option value="">{t("chooseModel")}</option>{models.map((item)=><option key={item.model} value={item.model}>{item.model}</option>)}</select></label><button className="icon-btn" onClick={()=>setMembers((items)=>items.filter((item)=>item.id!==member.id))} aria-label={t("remove")}><Trash size={15}/></button></div>)}</div><div className="collab-run"><textarea value={input} onChange={(e)=>setInput(e.target.value)} placeholder={t("collabInput")}/><button className="send-btn" disabled={!task||running} onClick={run}><Play size={16} weight="fill"/>{t("runWorkflow")}</button></div>{!task&&<div className="empty-warning"><WarningCircle size={15}/>{t("createTaskFirst")}</div>}</div>; }

function ContextPanel({tab,setTab,rpc}) { return <aside className="context-panel"><div className="context-tabs"><button className={tab==="files"?"active":""} onClick={()=>setTab("files")}><Folder size={15}/>Files</button><button className={tab==="diff"?"active":""} onClick={()=>setTab("diff")}><GitDiff size={15}/>Diff</button><button className={tab==="verify"?"active":""} onClick={()=>setTab("verify")}><CheckCircle size={15}/>Verify</button></div>{tab==="files"&&<FilesPanel rpc={rpc}/>} {tab==="diff"&&<DiffPanel rpc={rpc}/>} {tab==="verify"&&<VerifyPanel rpc={rpc}/>}</aside>; }
function FilesPanel({rpc}) { const {t}=useI18n();const [entries,setEntries]=useState([]);const [preview,setPreview]=useState(null);const load=()=>rpc("files.list",{path:"."}).then((x)=>setEntries(x.entries)).catch(()=>{});useEffect(load,[]);return <div className="context-body"><div className="context-title"><strong>{t("files")}</strong><button className="icon-btn" onClick={load}><CircleNotch size={14}/></button></div>{entries.map((entry)=><button className="file-row" key={entry.path} onClick={()=>entry.directory?null:rpc("files.read",{path:entry.path}).then(setPreview)}>{entry.directory?<Folder size={15}/>:<File size={15}/>} {entry.name}</button>)}{preview&&<pre className="file-preview">{preview.text}</pre>}</div>; }
function DiffPanel({rpc}) { const {t}=useI18n();const [value,setValue]=useState("");const load=()=>rpc("git.diff").then((x)=>setValue(x.unstaged+"\\n"+x.staged+"\\n"+(x.untracked||[]).join("\\n"))).catch((e)=>setValue(e.message));useEffect(load,[]);return <div className="context-body"><div className="context-title"><strong>{t("diff")}</strong><button className="icon-btn" onClick={load}><CircleNotch size={14}/></button></div><pre className="diff-preview">{value||t("noChanges")}</pre></div>; }
function VerifyPanel({rpc}) { const {t}=useI18n();const [checks,setChecks]=useState([]);const [result,setResult]=useState(null);useEffect(()=>{rpc("verify.list").then(setChecks).catch(()=>{});},[]);return <div className="context-body"><div className="context-title"><strong>{t("verify")}</strong></div>{checks.map((check)=><button key={check.id} className="review-btn" onClick={()=>rpc("verify.run",{script:check.id,command:check.command}).then(setResult)}><Play size={14} weight="fill"/>{check.id}</button>)}{result&&<pre className="verify-preview">{result.output||t("ready")}</pre>}</div>; }
function AgentsPanel({snapshot,rpc,refresh,log,onError}) { const {t}=useI18n(); async function install(id){try{await rpc("agents.install",{adapterId:id,confirm:true});await refresh();}catch(e){onError(e.message);}} async function status(id){try{onError((await rpc("agents.status",{adapterId:id})).text);}catch(e){onError(e.message);}} async function login(agent){try{const result=await rpc("agents.login",{adapterId:agent.id,method:agent.auth?.[0]?.id||"native"});onError(t("loginStarted")+" "+(result.id||""));}catch(e){onError(e.message);}} return <div className="agent-panel">{(snapshot?.agents||[]).map((agent)=><div className="agent-row" key={agent.id}><div><strong>{agent.name}</strong><span>{agent.installed?t("installed"):t("notInstalled")}</span></div><div className="agent-actions">{!agent.installed&&<button className="compact-btn" onClick={()=>install(agent.id)}><Plus size={14}/>{t("install")}</button>}{agent.installed&&<button className="compact-btn" onClick={()=>login(agent)}><ShieldCheck size={14}/>{t("login")}</button>}<button className="compact-btn" onClick={()=>status(agent.id)}><ShieldCheck size={14}/>{t("authStatus")}</button></div></div>)}{log.length>0&&<pre className="agent-log">{log.map((item)=>item.output||item.status).join("\n")}</pre>}</div>; }
function HistoryPanel({rpc,model,onSelect,onError}) { const {t}=useI18n(); const [items,setItems]=useState([]); useEffect(()=>{rpc("history.list").then(setItems).catch((error)=>onError(error.message));},[]); async function resume(item){try{const task=await rpc("history.import",{id:item.id,model});onSelect({id:task.id});}catch(error){onError(error.message);}} return <div className="history-panel">{items.length===0&&<div className="sidebar-empty">{t("noHistory")}</div>}{items.map((item)=><button className="history-row" key={item.id} onClick={()=>resume(item)}><div><strong>{item.title}</strong><span>{item.source} · {item.turnCount||item.turns?.length||0} {t("turns")}</span></div><ArrowRight size={14}/></button>)}</div>; }
function SettingsPanel({snapshot,url,rpc,refresh}) { const {preference,languages,setLanguage,t}=useI18n(); const [path,setPath]=useState(snapshot?.cwd||""); const [name,setName]=useState(""); const [baseUrl,setBaseUrl]=useState(""); const [apiKey,setApiKey]=useState(""); const [modelId,setModelId]=useState(""); async function open(){try{await rpc("workspace.open",{path});await refresh();}catch(error){window.alert(error.message);}} async function saveProvider(){try{await rpc("providers.save",{apiKey,profile:{id:crypto.randomUUID(),name,kind:"custom",baseUrl,models:[{id:modelId,agent:"dsh",protocol:"openai"}]}});setApiKey("");await refresh();}catch(error){window.alert(error.message);}} return <div className="settings-panel"><label className="workspace-input">{t("workspacePath")}<input value={path} onChange={(e)=>setPath(e.target.value)} placeholder="/Users/you/project" /><button className="compact-btn" onClick={open}>{t("openWorkspace")}</button></label><div className="provider-form"><strong>{t("addProvider")}</strong><input placeholder={t("providerName")} value={name} onChange={(e)=>setName(e.target.value)}/><input placeholder="https://api.example.com" value={baseUrl} onChange={(e)=>setBaseUrl(e.target.value)}/><input placeholder="model-id" value={modelId} onChange={(e)=>setModelId(e.target.value)}/><input placeholder={t("apiKey")} type="password" value={apiKey} onChange={(e)=>setApiKey(e.target.value)}/><button className="compact-btn" onClick={saveProvider}>{t("saveProvider")}</button></div><p>{t("server")}: <code>{url||t("offline")}</code></p><p>{snapshot?.trusted?t("workspaceTrusted"):t("workspaceNeedsTrust")}</p><label className="settings-language">{t("language")}<select value={preference} onChange={(e)=>setLanguage(e.target.value)}>{languages.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><button className="compact-btn" onClick={refresh}><CircleNotch size={14}/>{t("refresh")}</button></div>; }
function CommandPalette({open,setOpen,onNew,onAgents,onSettings,onContext}) { const {t}=useI18n();return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Overlay className="command-overlay"/><Dialog.Content className="command-dialog"><Dialog.Title className="sr-only">{t("commandPalette")}</Dialog.Title><Command label="habor commands"><Command.Input placeholder={t("commandSearch")} autoFocus/><Command.List><Command.Empty>{t("noResults")}</Command.Empty><Command.Group heading={t("navigate")}><Command.Item onSelect={()=>{setOpen(false);onNew();}}>{t("newTask")}</Command.Item><Command.Item onSelect={()=>{setOpen(false);onContext("files");}}>{t("showFiles")}</Command.Item><Command.Item onSelect={()=>{setOpen(false);onContext("diff");}}>{t("showDiff")}</Command.Item><Command.Item onSelect={()=>{setOpen(false);onContext("verify");}}>{t("showVerify")}</Command.Item><Command.Item onSelect={()=>{setOpen(false);onAgents();}}>{t("agentsAndModels")}</Command.Item><Command.Item onSelect={()=>{setOpen(false);onSettings();}}>{t("settings")}</Command.Item></Command.Group></Command.List></Command></Dialog.Content></Dialog.Portal></Dialog.Root>; }
