#!/usr/bin/env node
// Replay both notifications generated by one failing Codex turn.
const readline = require('node:readline');
const send = value => process.stdout.write(JSON.stringify(value) + '\n');
let turn = 0;
readline.createInterface({ input:process.stdin }).on('line', line => {
  const request = JSON.parse(line);
  if (request.method === 'initialize') send({id:request.id,result:{}});
  if (request.method === 'thread/start') send({id:request.id,result:{model:request.params.model,modelProvider:'openai',thread:{id:'mock-thread'}}});
  if (request.method === 'turn/start') {
    const id = `turn-${++turn}`;
    send({id:request.id,result:{turn:{id}}});
    if (turn <= 2) {
      const message = JSON.stringify({type:'error',status:400,error:{type:'invalid_request_error',message:"The 'gpt-6-astra' model requires a newer version of Codex. Please upgrade to the latest app or CLI and try again."}});
      send({method:'error',params:{threadId:'mock-thread',turnId:id,willRetry:false,error:{message}}});
      send({method:'turn/completed',params:{threadId:'mock-thread',turn:{id,status:'failed',error:{message}}}});
    } else {
      send({method:'item/agentMessage/delta',params:{threadId:'mock-thread',itemId:'message',delta:'Recovered'}});
      send({method:'turn/completed',params:{threadId:'mock-thread',turn:{id,status:'completed',error:null}}});
    }
  }
});
